name: Java CI with Maven & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.VPS_HOST}}
          username: ${{secrets.VPS_USERNAME}}
          port: ${{secrets.VPS_PORT}}
          password: ${{secrets.VPS_PASSWORD}}
          source: "./target/simbot-mirai-demo-2.0.5.jar"
          target: "/simple-robot/"
          strip_components: 2

      - name: log untrusted output
          run: |

            # disable command workflow processing
            echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

            # log untrusted output
            echo "untrusted output"

            # enable workflow command processing
            echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"

      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup knownhosts
        run: ssh-keyscan ${{secrets.VPS_HOST}} >> ~/.ssh/known_hosts

      - name: Run SSH Command
        run: |
          ssh root@${{secrets.VPS_HOST}} "echo 'Hello Github Actions' > actions.log"
          ssh root@${{secrets.VPS_HOST}} "cd /simple-robot"
          ssh root@${{secrets.VPS_HOST}} "nohup java -jar simbot-mirai-demo-2.0.5.jar > log.file  2>&1 &"