name: Java CI with Maven & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.VPS_HOST}}
          username: ${{secrets.VPS_USERNAME}}
          port: ${{secrets.VPS_PORT}}
          password: ${{secrets.VPS_PASSWORD}}
          source: "./target/simbot-mirai-demo-2.0.5.jar"
          target: "/simple-robot/"
          strip_components: 2